export const SPORTS = {
  tennis: {
    id: 'tennis',
    label: 'Tennis',
    icon: '🎾',
    courtType: 'tennis',
    maxPerTeam: 2,
    theme: null,
  },
  padel: {
    id: 'padel',
    label: 'Padel',
    icon: '🏓',
    courtType: 'padel',
    maxPerTeam: 2,
    theme: {
      court: '#2E8B6E',
      courtLight: '#3AAD88',
      lines: '#FFFFFF',
      net: '#FFFFFF',
      surrounds: '#1A5C4A',
      drawColour: '#FFE600',
      background: '#0a1a14',
    },
  },
  football: {
    id: 'football',
    label: 'Football',
    icon: '⚽',
    courtType: 'football',
    maxPerTeam: 11,
    theme: {
      court: '#2E7D32',
      courtLight: '#388E3C',
      lines: '#FFFFFF',
      net: '#FFFFFF',
      surrounds: '#1B5E20',
      drawColour: '#FFFF00',
      background: '#0a1a0a',
    },
  },
  field_hockey: {
    id: 'field_hockey',
    label: 'Field Hockey',
    icon: '🏑',
    courtType: 'field_hockey',
    maxPerTeam: 11,
    theme: {
      court: '#1565C0',
      courtLight: '#1976D2',
      lines: '#FFFFFF',
      net: '#FFFFFF',
      surrounds: '#0D3B7A',
      drawColour: '#FF6D00',
      background: '#060d1f',
    },
  },
  ice_hockey: {
    id: 'ice_hockey',
    label: 'Ice Hockey',
    icon: '🏒',
    courtType: 'ice_hockey',
    maxPerTeam: 6,
    theme: {
      court: '#E3F2FD',
      courtLight: '#FFFFFF',
      lines: '#1565C0',
      net: '#D32F2F',
      surrounds: '#90CAF9',
      drawColour: '#D32F2F',
      background: '#1a2a3a',
    },
  },
  basketball: {
    id: 'basketball',
    label: 'Basketball',
    icon: '🏀',
    courtType: 'basketball',
    maxPerTeam: 5,
    theme: {
      court: '#C8843A',
      courtLight: '#D4944A',
      lines: '#FFFFFF',
      net: '#FFFFFF',
      surrounds: '#8B5E27',
      drawColour: '#FF6B00',
      background: '#1a0f05',
    },
  },
  volleyball: {
    id: 'volleyball',
    label: 'Volleyball',
    icon: '🏐',
    courtType: 'volleyball',
    maxPerTeam: 6,
    theme: {
      court: '#5C9BD6',
      courtLight: '#76B3E8',
      lines: '#FFFFFF',
      net: '#FFFFFF',
      surrounds: '#2E6DA4',
      drawColour: '#FFE600',
      background: '#0a1428',
    },
  },
  baseball: {
    id: 'baseball',
    label: 'Baseball',
    icon: '⚾',
    courtType: 'baseball',
    maxPerTeam: 9,
    theme: {
      court: '#2E7D32',
      courtLight: '#C2915A',
      lines: '#FFFFFF',
      net: '#FFFFFF',
      surrounds: '#1B5E20',
      drawColour: '#FFFFFF',
      background: '#0a1a0a',
    },
  },
};

export const SPORT_IDS = [
  'tennis',
  'padel',
  'football',
  'field_hockey',
  'ice_hockey',
  'basketball',
  'volleyball',
  'baseball',
];

export const DEFAULT_SPORT = 'tennis';
